version: '3.7'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/delivery_test
    ports:
      - "80:3000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust